version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: directory_service_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  seq:
    image: datalust/seq:latest
    container_name: directory_service_seq
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_NOAUTHENTICATION: "true"
    ports:
      - "8081:80"
      - "5343:5341"
    volumes:
      - seq_data:/data

volumes:
  postgres_data:
  seq_data:
